// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: proto/v3/sat.proto

package v3

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReferenceFrame int32

const (
	ReferenceFrame_REFERENCE_FRAME_UNSPECIFIED ReferenceFrame = 0
	ReferenceFrame_REFERENCE_FRAME_TEME        ReferenceFrame = 1 // SGP4 native
	ReferenceFrame_REFERENCE_FRAME_ECI         ReferenceFrame = 2
	ReferenceFrame_REFERENCE_FRAME_ECEF        ReferenceFrame = 3
)

// Enum value maps for ReferenceFrame.
var (
	ReferenceFrame_name = map[int32]string{
		0: "REFERENCE_FRAME_UNSPECIFIED",
		1: "REFERENCE_FRAME_TEME",
		2: "REFERENCE_FRAME_ECI",
		3: "REFERENCE_FRAME_ECEF",
	}
	ReferenceFrame_value = map[string]int32{
		"REFERENCE_FRAME_UNSPECIFIED": 0,
		"REFERENCE_FRAME_TEME":        1,
		"REFERENCE_FRAME_ECI":         2,
		"REFERENCE_FRAME_ECEF":        3,
	}
)

func (x ReferenceFrame) Enum() *ReferenceFrame {
	p := new(ReferenceFrame)
	*p = x
	return p
}

func (x ReferenceFrame) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReferenceFrame) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_v3_sat_proto_enumTypes[0].Descriptor()
}

func (ReferenceFrame) Type() protoreflect.EnumType {
	return &file_proto_v3_sat_proto_enumTypes[0]
}

func (x ReferenceFrame) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReferenceFrame.Descriptor instead.
func (ReferenceFrame) EnumDescriptor() ([]byte, []int) {
	return file_proto_v3_sat_proto_rawDescGZIP(), []int{0}
}

type PropagatorType int32

const (
	PropagatorType_PROPAGATOR_TYPE_UNSPECIFIED PropagatorType = 0
	PropagatorType_PROPAGATOR_TYPE_SGP4        PropagatorType = 1
	PropagatorType_PROPAGATOR_TYPE_SDP4        PropagatorType = 2
	PropagatorType_PROPAGATOR_TYPE_NUMERICAL   PropagatorType = 3
)

// Enum value maps for PropagatorType.
var (
	PropagatorType_name = map[int32]string{
		0: "PROPAGATOR_TYPE_UNSPECIFIED",
		1: "PROPAGATOR_TYPE_SGP4",
		2: "PROPAGATOR_TYPE_SDP4",
		3: "PROPAGATOR_TYPE_NUMERICAL",
	}
	PropagatorType_value = map[string]int32{
		"PROPAGATOR_TYPE_UNSPECIFIED": 0,
		"PROPAGATOR_TYPE_SGP4":        1,
		"PROPAGATOR_TYPE_SDP4":        2,
		"PROPAGATOR_TYPE_NUMERICAL":   3,
	}
)

func (x PropagatorType) Enum() *PropagatorType {
	p := new(PropagatorType)
	*p = x
	return p
}

func (x PropagatorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PropagatorType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_v3_sat_proto_enumTypes[1].Descriptor()
}

func (PropagatorType) Type() protoreflect.EnumType {
	return &file_proto_v3_sat_proto_enumTypes[1]
}

func (x PropagatorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PropagatorType.Descriptor instead.
func (PropagatorType) EnumDescriptor() ([]byte, []int) {
	return file_proto_v3_sat_proto_rawDescGZIP(), []int{1}
}

type Tle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Line1         string                 `protobuf:"bytes,1,opt,name=line1,proto3" json:"line1,omitempty"`
	Line2         string                 `protobuf:"bytes,2,opt,name=line2,proto3" json:"line2,omitempty"`
	SatelliteName string                 `protobuf:"bytes,3,opt,name=satellite_name,json=satelliteName,proto3" json:"satellite_name,omitempty"`
	// NORAD catalog number
	SatelliteNumber uint32 `protobuf:"varint,4,opt,name=satellite_number,json=satelliteNumber,proto3" json:"satellite_number,omitempty"`
	// Epoch extracted from TLE
	Epoch         *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=epoch,proto3" json:"epoch,omitempty"`
	OrbitElements *OrbitElements         `protobuf:"bytes,6,opt,name=orbit_elements,json=orbitElements,proto3" json:"orbit_elements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tle) Reset() {
	*x = Tle{}
	mi := &file_proto_v3_sat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tle) ProtoMessage() {}

func (x *Tle) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v3_sat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tle.ProtoReflect.Descriptor instead.
func (*Tle) Descriptor() ([]byte, []int) {
	return file_proto_v3_sat_proto_rawDescGZIP(), []int{0}
}

func (x *Tle) GetLine1() string {
	if x != nil {
		return x.Line1
	}
	return ""
}

func (x *Tle) GetLine2() string {
	if x != nil {
		return x.Line2
	}
	return ""
}

func (x *Tle) GetSatelliteName() string {
	if x != nil {
		return x.SatelliteName
	}
	return ""
}

func (x *Tle) GetSatelliteNumber() uint32 {
	if x != nil {
		return x.SatelliteNumber
	}
	return 0
}

func (x *Tle) GetEpoch() *timestamppb.Timestamp {
	if x != nil {
		return x.Epoch
	}
	return nil
}

func (x *Tle) GetOrbitElements() *OrbitElements {
	if x != nil {
		return x.OrbitElements
	}
	return nil
}

type Vector3 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"` // km
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"` // km
	Z             float64                `protobuf:"fixed64,3,opt,name=z,proto3" json:"z,omitempty"` // km
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vector3) Reset() {
	*x = Vector3{}
	mi := &file_proto_v3_sat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector3) ProtoMessage() {}

func (x *Vector3) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v3_sat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector3.ProtoReflect.Descriptor instead.
func (*Vector3) Descriptor() ([]byte, []int) {
	return file_proto_v3_sat_proto_rawDescGZIP(), []int{1}
}

func (x *Vector3) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vector3) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Vector3) GetZ() float64 {
	if x != nil {
		return x.Z
	}
	return 0
}

type StateVector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      *Vector3               `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"` // km
	Velocity      *Vector3               `protobuf:"bytes,2,opt,name=velocity,proto3" json:"velocity,omitempty"` // km/s
	Frame         ReferenceFrame         `protobuf:"varint,3,opt,name=frame,proto3,enum=orbit.ReferenceFrame" json:"frame,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateVector) Reset() {
	*x = StateVector{}
	mi := &file_proto_v3_sat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateVector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateVector) ProtoMessage() {}

func (x *StateVector) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v3_sat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateVector.ProtoReflect.Descriptor instead.
func (*StateVector) Descriptor() ([]byte, []int) {
	return file_proto_v3_sat_proto_rawDescGZIP(), []int{2}
}

func (x *StateVector) GetPosition() *Vector3 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *StateVector) GetVelocity() *Vector3 {
	if x != nil {
		return x.Velocity
	}
	return nil
}

func (x *StateVector) GetFrame() ReferenceFrame {
	if x != nil {
		return x.Frame
	}
	return ReferenceFrame_REFERENCE_FRAME_UNSPECIFIED
}

type GeodeticPosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LatitudeDeg   float64                `protobuf:"fixed64,1,opt,name=latitude_deg,json=latitudeDeg,proto3" json:"latitude_deg,omitempty"`
	LongitudeDeg  float64                `protobuf:"fixed64,2,opt,name=longitude_deg,json=longitudeDeg,proto3" json:"longitude_deg,omitempty"`
	AltitudeKm    float64                `protobuf:"fixed64,3,opt,name=altitude_km,json=altitudeKm,proto3" json:"altitude_km,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeodeticPosition) Reset() {
	*x = GeodeticPosition{}
	mi := &file_proto_v3_sat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeodeticPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeodeticPosition) ProtoMessage() {}

func (x *GeodeticPosition) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v3_sat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeodeticPosition.ProtoReflect.Descriptor instead.
func (*GeodeticPosition) Descriptor() ([]byte, []int) {
	return file_proto_v3_sat_proto_rawDescGZIP(), []int{3}
}

func (x *GeodeticPosition) GetLatitudeDeg() float64 {
	if x != nil {
		return x.LatitudeDeg
	}
	return 0
}

func (x *GeodeticPosition) GetLongitudeDeg() float64 {
	if x != nil {
		return x.LongitudeDeg
	}
	return 0
}

func (x *GeodeticPosition) GetAltitudeKm() float64 {
	if x != nil {
		return x.AltitudeKm
	}
	return 0
}

type OrbitElements struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	SemiMajorAxisKm      float64                `protobuf:"fixed64,1,opt,name=semi_major_axis_km,json=semiMajorAxisKm,proto3" json:"semi_major_axis_km,omitempty"`
	Eccentricity         float64                `protobuf:"fixed64,2,opt,name=eccentricity,proto3" json:"eccentricity,omitempty"`
	InclinationDeg       float64                `protobuf:"fixed64,3,opt,name=inclination_deg,json=inclinationDeg,proto3" json:"inclination_deg,omitempty"`
	RaanDeg              float64                `protobuf:"fixed64,4,opt,name=raan_deg,json=raanDeg,proto3" json:"raan_deg,omitempty"`
	ArgumentOfPerigeeDeg float64                `protobuf:"fixed64,5,opt,name=argument_of_perigee_deg,json=argumentOfPerigeeDeg,proto3" json:"argument_of_perigee_deg,omitempty"`
	TrueAnomalyDeg       float64                `protobuf:"fixed64,6,opt,name=true_anomaly_deg,json=trueAnomalyDeg,proto3" json:"true_anomaly_deg,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *OrbitElements) Reset() {
	*x = OrbitElements{}
	mi := &file_proto_v3_sat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrbitElements) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrbitElements) ProtoMessage() {}

func (x *OrbitElements) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v3_sat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrbitElements.ProtoReflect.Descriptor instead.
func (*OrbitElements) Descriptor() ([]byte, []int) {
	return file_proto_v3_sat_proto_rawDescGZIP(), []int{4}
}

func (x *OrbitElements) GetSemiMajorAxisKm() float64 {
	if x != nil {
		return x.SemiMajorAxisKm
	}
	return 0
}

func (x *OrbitElements) GetEccentricity() float64 {
	if x != nil {
		return x.Eccentricity
	}
	return 0
}

func (x *OrbitElements) GetInclinationDeg() float64 {
	if x != nil {
		return x.InclinationDeg
	}
	return 0
}

func (x *OrbitElements) GetRaanDeg() float64 {
	if x != nil {
		return x.RaanDeg
	}
	return 0
}

func (x *OrbitElements) GetArgumentOfPerigeeDeg() float64 {
	if x != nil {
		return x.ArgumentOfPerigeeDeg
	}
	return 0
}

func (x *OrbitElements) GetTrueAnomalyDeg() float64 {
	if x != nil {
		return x.TrueAnomalyDeg
	}
	return 0
}

type Propagation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	State         *StateVector           `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Geodetic      *GeodeticPosition      `protobuf:"bytes,3,opt,name=geodetic,proto3" json:"geodetic,omitempty"`
	Propagator    PropagatorType         `protobuf:"varint,4,opt,name=propagator,proto3,enum=orbit.PropagatorType" json:"propagator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Propagation) Reset() {
	*x = Propagation{}
	mi := &file_proto_v3_sat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Propagation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Propagation) ProtoMessage() {}

func (x *Propagation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v3_sat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Propagation.ProtoReflect.Descriptor instead.
func (*Propagation) Descriptor() ([]byte, []int) {
	return file_proto_v3_sat_proto_rawDescGZIP(), []int{5}
}

func (x *Propagation) GetEpoch() *timestamppb.Timestamp {
	if x != nil {
		return x.Epoch
	}
	return nil
}

func (x *Propagation) GetState() *StateVector {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *Propagation) GetGeodetic() *GeodeticPosition {
	if x != nil {
		return x.Geodetic
	}
	return nil
}

func (x *Propagation) GetPropagator() PropagatorType {
	if x != nil {
		return x.Propagator
	}
	return PropagatorType_PROPAGATOR_TYPE_UNSPECIFIED
}

type GetPropagationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// NORAD catalog number
	SatelliteNumber uint32 `protobuf:"varint,1,opt,name=satellite_number,json=satelliteNumber,proto3" json:"satellite_number,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetPropagationRequest) Reset() {
	*x = GetPropagationRequest{}
	mi := &file_proto_v3_sat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPropagationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPropagationRequest) ProtoMessage() {}

func (x *GetPropagationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v3_sat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPropagationRequest.ProtoReflect.Descriptor instead.
func (*GetPropagationRequest) Descriptor() ([]byte, []int) {
	return file_proto_v3_sat_proto_rawDescGZIP(), []int{6}
}

func (x *GetPropagationRequest) GetSatelliteNumber() uint32 {
	if x != nil {
		return x.SatelliteNumber
	}
	return 0
}

type GetPropagationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Original TLE
	Tle *Tle `protobuf:"bytes,1,opt,name=tle,proto3" json:"tle,omitempty"`
	// Age of TLE relative to "now"
	TleAge *durationpb.Duration `protobuf:"bytes,2,opt,name=tle_age,json=tleAge,proto3" json:"tle_age,omitempty"`
	// Propagation exactly at TLE epoch
	AtTleEpoch *Propagation `protobuf:"bytes,3,opt,name=at_tle_epoch,json=atTleEpoch,proto3" json:"at_tle_epoch,omitempty"`
	// Propagation at request time (UTC now)
	AtNowUtc *Propagation `protobuf:"bytes,4,opt,name=at_now_utc,json=atNowUtc,proto3" json:"at_now_utc,omitempty"`
	// Arbitrary N propagations
	Propagations  []*Propagation `protobuf:"bytes,5,rep,name=propagations,proto3" json:"propagations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPropagationResponse) Reset() {
	*x = GetPropagationResponse{}
	mi := &file_proto_v3_sat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPropagationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPropagationResponse) ProtoMessage() {}

func (x *GetPropagationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v3_sat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPropagationResponse.ProtoReflect.Descriptor instead.
func (*GetPropagationResponse) Descriptor() ([]byte, []int) {
	return file_proto_v3_sat_proto_rawDescGZIP(), []int{7}
}

func (x *GetPropagationResponse) GetTle() *Tle {
	if x != nil {
		return x.Tle
	}
	return nil
}

func (x *GetPropagationResponse) GetTleAge() *durationpb.Duration {
	if x != nil {
		return x.TleAge
	}
	return nil
}

func (x *GetPropagationResponse) GetAtTleEpoch() *Propagation {
	if x != nil {
		return x.AtTleEpoch
	}
	return nil
}

func (x *GetPropagationResponse) GetAtNowUtc() *Propagation {
	if x != nil {
		return x.AtNowUtc
	}
	return nil
}

func (x *GetPropagationResponse) GetPropagations() []*Propagation {
	if x != nil {
		return x.Propagations
	}
	return nil
}

var File_proto_v3_sat_proto protoreflect.FileDescriptor

const file_proto_v3_sat_proto_rawDesc = "" +
	"\n" +
	"\x12proto/v3/sat.proto\x12\x05orbit\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf2\x01\n" +
	"\x03Tle\x12\x14\n" +
	"\x05line1\x18\x01 \x01(\tR\x05line1\x12\x14\n" +
	"\x05line2\x18\x02 \x01(\tR\x05line2\x12%\n" +
	"\x0esatellite_name\x18\x03 \x01(\tR\rsatelliteName\x12)\n" +
	"\x10satellite_number\x18\x04 \x01(\rR\x0fsatelliteNumber\x120\n" +
	"\x05epoch\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x05epoch\x12;\n" +
	"\x0eorbit_elements\x18\x06 \x01(\v2\x14.orbit.OrbitElementsR\rorbitElements\"3\n" +
	"\aVector3\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x01R\x01z\"\x92\x01\n" +
	"\vStateVector\x12*\n" +
	"\bposition\x18\x01 \x01(\v2\x0e.orbit.Vector3R\bposition\x12*\n" +
	"\bvelocity\x18\x02 \x01(\v2\x0e.orbit.Vector3R\bvelocity\x12+\n" +
	"\x05frame\x18\x03 \x01(\x0e2\x15.orbit.ReferenceFrameR\x05frame\"{\n" +
	"\x10GeodeticPosition\x12!\n" +
	"\flatitude_deg\x18\x01 \x01(\x01R\vlatitudeDeg\x12#\n" +
	"\rlongitude_deg\x18\x02 \x01(\x01R\flongitudeDeg\x12\x1f\n" +
	"\valtitude_km\x18\x03 \x01(\x01R\n" +
	"altitudeKm\"\x85\x02\n" +
	"\rOrbitElements\x12+\n" +
	"\x12semi_major_axis_km\x18\x01 \x01(\x01R\x0fsemiMajorAxisKm\x12\"\n" +
	"\feccentricity\x18\x02 \x01(\x01R\feccentricity\x12'\n" +
	"\x0finclination_deg\x18\x03 \x01(\x01R\x0einclinationDeg\x12\x19\n" +
	"\braan_deg\x18\x04 \x01(\x01R\araanDeg\x125\n" +
	"\x17argument_of_perigee_deg\x18\x05 \x01(\x01R\x14argumentOfPerigeeDeg\x12(\n" +
	"\x10true_anomaly_deg\x18\x06 \x01(\x01R\x0etrueAnomalyDeg\"\xd5\x01\n" +
	"\vPropagation\x120\n" +
	"\x05epoch\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x05epoch\x12(\n" +
	"\x05state\x18\x02 \x01(\v2\x12.orbit.StateVectorR\x05state\x123\n" +
	"\bgeodetic\x18\x03 \x01(\v2\x17.orbit.GeodeticPositionR\bgeodetic\x125\n" +
	"\n" +
	"propagator\x18\x04 \x01(\x0e2\x15.orbit.PropagatorTypeR\n" +
	"propagator\"B\n" +
	"\x15GetPropagationRequest\x12)\n" +
	"\x10satellite_number\x18\x01 \x01(\rR\x0fsatelliteNumber\"\x8a\x02\n" +
	"\x16GetPropagationResponse\x12\x1c\n" +
	"\x03tle\x18\x01 \x01(\v2\n" +
	".orbit.TleR\x03tle\x122\n" +
	"\atle_age\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x06tleAge\x124\n" +
	"\fat_tle_epoch\x18\x03 \x01(\v2\x12.orbit.PropagationR\n" +
	"atTleEpoch\x120\n" +
	"\n" +
	"at_now_utc\x18\x04 \x01(\v2\x12.orbit.PropagationR\batNowUtc\x126\n" +
	"\fpropagations\x18\x05 \x03(\v2\x12.orbit.PropagationR\fpropagations*~\n" +
	"\x0eReferenceFrame\x12\x1f\n" +
	"\x1bREFERENCE_FRAME_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14REFERENCE_FRAME_TEME\x10\x01\x12\x17\n" +
	"\x13REFERENCE_FRAME_ECI\x10\x02\x12\x18\n" +
	"\x14REFERENCE_FRAME_ECEF\x10\x03*\x84\x01\n" +
	"\x0ePropagatorType\x12\x1f\n" +
	"\x1bPROPAGATOR_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14PROPAGATOR_TYPE_SGP4\x10\x01\x12\x18\n" +
	"\x14PROPAGATOR_TYPE_SDP4\x10\x02\x12\x1d\n" +
	"\x19PROPAGATOR_TYPE_NUMERICAL\x10\x032c\n" +
	"\x12PropagationService\x12M\n" +
	"\x0eGetPropagation\x12\x1c.orbit.GetPropagationRequest\x1a\x1d.orbit.GetPropagationResponseB\n" +
	"Z\bproto/v3b\x06proto3"

var (
	file_proto_v3_sat_proto_rawDescOnce sync.Once
	file_proto_v3_sat_proto_rawDescData []byte
)

func file_proto_v3_sat_proto_rawDescGZIP() []byte {
	file_proto_v3_sat_proto_rawDescOnce.Do(func() {
		file_proto_v3_sat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v3_sat_proto_rawDesc), len(file_proto_v3_sat_proto_rawDesc)))
	})
	return file_proto_v3_sat_proto_rawDescData
}

var file_proto_v3_sat_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_v3_sat_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_v3_sat_proto_goTypes = []any{
	(ReferenceFrame)(0),            // 0: orbit.ReferenceFrame
	(PropagatorType)(0),            // 1: orbit.PropagatorType
	(*Tle)(nil),                    // 2: orbit.Tle
	(*Vector3)(nil),                // 3: orbit.Vector3
	(*StateVector)(nil),            // 4: orbit.StateVector
	(*GeodeticPosition)(nil),       // 5: orbit.GeodeticPosition
	(*OrbitElements)(nil),          // 6: orbit.OrbitElements
	(*Propagation)(nil),            // 7: orbit.Propagation
	(*GetPropagationRequest)(nil),  // 8: orbit.GetPropagationRequest
	(*GetPropagationResponse)(nil), // 9: orbit.GetPropagationResponse
	(*timestamppb.Timestamp)(nil),  // 10: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),    // 11: google.protobuf.Duration
}
var file_proto_v3_sat_proto_depIdxs = []int32{
	10, // 0: orbit.Tle.epoch:type_name -> google.protobuf.Timestamp
	6,  // 1: orbit.Tle.orbit_elements:type_name -> orbit.OrbitElements
	3,  // 2: orbit.StateVector.position:type_name -> orbit.Vector3
	3,  // 3: orbit.StateVector.velocity:type_name -> orbit.Vector3
	0,  // 4: orbit.StateVector.frame:type_name -> orbit.ReferenceFrame
	10, // 5: orbit.Propagation.epoch:type_name -> google.protobuf.Timestamp
	4,  // 6: orbit.Propagation.state:type_name -> orbit.StateVector
	5,  // 7: orbit.Propagation.geodetic:type_name -> orbit.GeodeticPosition
	1,  // 8: orbit.Propagation.propagator:type_name -> orbit.PropagatorType
	2,  // 9: orbit.GetPropagationResponse.tle:type_name -> orbit.Tle
	11, // 10: orbit.GetPropagationResponse.tle_age:type_name -> google.protobuf.Duration
	7,  // 11: orbit.GetPropagationResponse.at_tle_epoch:type_name -> orbit.Propagation
	7,  // 12: orbit.GetPropagationResponse.at_now_utc:type_name -> orbit.Propagation
	7,  // 13: orbit.GetPropagationResponse.propagations:type_name -> orbit.Propagation
	8,  // 14: orbit.PropagationService.GetPropagation:input_type -> orbit.GetPropagationRequest
	9,  // 15: orbit.PropagationService.GetPropagation:output_type -> orbit.GetPropagationResponse
	15, // [15:16] is the sub-list for method output_type
	14, // [14:15] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_proto_v3_sat_proto_init() }
func file_proto_v3_sat_proto_init() {
	if File_proto_v3_sat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v3_sat_proto_rawDesc), len(file_proto_v3_sat_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v3_sat_proto_goTypes,
		DependencyIndexes: file_proto_v3_sat_proto_depIdxs,
		EnumInfos:         file_proto_v3_sat_proto_enumTypes,
		MessageInfos:      file_proto_v3_sat_proto_msgTypes,
	}.Build()
	File_proto_v3_sat_proto = out.File
	file_proto_v3_sat_proto_goTypes = nil
	file_proto_v3_sat_proto_depIdxs = nil
}
