// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.31.1
// source: proto/v3/sat.proto

package v3

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PropagationService_GetPropagation_FullMethodName = "/api.v3.PropagationService/GetPropagation"
)

// PropagationServiceClient is the client API for PropagationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PropagationServiceClient interface {
	GetPropagation(ctx context.Context, in *GetPropagationRequest, opts ...grpc.CallOption) (*GetPropagationResponse, error)
}

type propagationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPropagationServiceClient(cc grpc.ClientConnInterface) PropagationServiceClient {
	return &propagationServiceClient{cc}
}

func (c *propagationServiceClient) GetPropagation(ctx context.Context, in *GetPropagationRequest, opts ...grpc.CallOption) (*GetPropagationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPropagationResponse)
	err := c.cc.Invoke(ctx, PropagationService_GetPropagation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PropagationServiceServer is the server API for PropagationService service.
// All implementations must embed UnimplementedPropagationServiceServer
// for forward compatibility.
type PropagationServiceServer interface {
	GetPropagation(context.Context, *GetPropagationRequest) (*GetPropagationResponse, error)
	mustEmbedUnimplementedPropagationServiceServer()
}

// UnimplementedPropagationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPropagationServiceServer struct{}

func (UnimplementedPropagationServiceServer) GetPropagation(context.Context, *GetPropagationRequest) (*GetPropagationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPropagation not implemented")
}
func (UnimplementedPropagationServiceServer) mustEmbedUnimplementedPropagationServiceServer() {}
func (UnimplementedPropagationServiceServer) testEmbeddedByValue()                            {}

// UnsafePropagationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PropagationServiceServer will
// result in compilation errors.
type UnsafePropagationServiceServer interface {
	mustEmbedUnimplementedPropagationServiceServer()
}

func RegisterPropagationServiceServer(s grpc.ServiceRegistrar, srv PropagationServiceServer) {
	// If the following call panics, it indicates UnimplementedPropagationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PropagationService_ServiceDesc, srv)
}

func _PropagationService_GetPropagation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPropagationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropagationServiceServer).GetPropagation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PropagationService_GetPropagation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropagationServiceServer).GetPropagation(ctx, req.(*GetPropagationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PropagationService_ServiceDesc is the grpc.ServiceDesc for PropagationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PropagationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.v3.PropagationService",
	HandlerType: (*PropagationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPropagation",
			Handler:    _PropagationService_GetPropagation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/v3/sat.proto",
}
