// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: proto/v2/sat.proto

// namespace

package v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PropogationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoradCategory int32                  `protobuf:"varint,1,opt,name=norad_category,json=noradCategory,proto3" json:"norad_category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PropogationRequest) Reset() {
	*x = PropogationRequest{}
	mi := &file_proto_v2_sat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropogationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropogationRequest) ProtoMessage() {}

func (x *PropogationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v2_sat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropogationRequest.ProtoReflect.Descriptor instead.
func (*PropogationRequest) Descriptor() ([]byte, []int) {
	return file_proto_v2_sat_proto_rawDescGZIP(), []int{0}
}

func (x *PropogationRequest) GetNoradCategory() int32 {
	if x != nil {
		return x.NoradCategory
	}
	return 0
}

type PropogationReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tle           *Tle                   `protobuf:"bytes,1,opt,name=tle,proto3" json:"tle,omitempty"`
	Propogations  []*Propogation         `protobuf:"bytes,2,rep,name=propogations,proto3" json:"propogations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PropogationReply) Reset() {
	*x = PropogationReply{}
	mi := &file_proto_v2_sat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropogationReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropogationReply) ProtoMessage() {}

func (x *PropogationReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v2_sat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropogationReply.ProtoReflect.Descriptor instead.
func (*PropogationReply) Descriptor() ([]byte, []int) {
	return file_proto_v2_sat_proto_rawDescGZIP(), []int{1}
}

func (x *PropogationReply) GetTle() *Tle {
	if x != nil {
		return x.Tle
	}
	return nil
}

func (x *PropogationReply) GetPropogations() []*Propogation {
	if x != nil {
		return x.Propogations
	}
	return nil
}

type Tle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Line1         string                 `protobuf:"bytes,2,opt,name=line1,proto3" json:"line1,omitempty"`
	Line2         string                 `protobuf:"bytes,3,opt,name=line2,proto3" json:"line2,omitempty"`
	Age           float32                `protobuf:"fixed32,4,opt,name=age,proto3" json:"age,omitempty"`
	Propogation   *Propogation           `protobuf:"bytes,5,opt,name=propogation,proto3" json:"propogation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tle) Reset() {
	*x = Tle{}
	mi := &file_proto_v2_sat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tle) ProtoMessage() {}

func (x *Tle) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v2_sat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tle.ProtoReflect.Descriptor instead.
func (*Tle) Descriptor() ([]byte, []int) {
	return file_proto_v2_sat_proto_rawDescGZIP(), []int{2}
}

func (x *Tle) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tle) GetLine1() string {
	if x != nil {
		return x.Line1
	}
	return ""
}

func (x *Tle) GetLine2() string {
	if x != nil {
		return x.Line2
	}
	return ""
}

func (x *Tle) GetAge() float32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *Tle) GetPropogation() *Propogation {
	if x != nil {
		return x.Propogation
	}
	return nil
}

type Propogation struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Timestamp int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// The latitude and longitude in degrees, using the WGS84 standard.
	// The latitude in degrees. It must be in the range [-90.0, +90.0].
	Latitude float64 `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	// The longitude in degrees. It must be in the range [-180.0, +180.0].
	Longitude float64 `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	// Using a float type for precision.
	// in meters
	Altitude      float32 `protobuf:"fixed32,4,opt,name=altitude,proto3" json:"altitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Propogation) Reset() {
	*x = Propogation{}
	mi := &file_proto_v2_sat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Propogation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Propogation) ProtoMessage() {}

func (x *Propogation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v2_sat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Propogation.ProtoReflect.Descriptor instead.
func (*Propogation) Descriptor() ([]byte, []int) {
	return file_proto_v2_sat_proto_rawDescGZIP(), []int{3}
}

func (x *Propogation) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Propogation) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Propogation) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Propogation) GetAltitude() float32 {
	if x != nil {
		return x.Altitude
	}
	return 0
}

var File_proto_v2_sat_proto protoreflect.FileDescriptor

const file_proto_v2_sat_proto_rawDesc = "" +
	"\n" +
	"\x12proto/v2/sat.proto\x12\bsatproto\";\n" +
	"\x12PropogationRequest\x12%\n" +
	"\x0enorad_category\x18\x01 \x01(\x05R\rnoradCategory\"n\n" +
	"\x10PropogationReply\x12\x1f\n" +
	"\x03tle\x18\x01 \x01(\v2\r.satproto.TleR\x03tle\x129\n" +
	"\fpropogations\x18\x02 \x03(\v2\x15.satproto.PropogationR\fpropogations\"\x90\x01\n" +
	"\x03Tle\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05line1\x18\x02 \x01(\tR\x05line1\x12\x14\n" +
	"\x05line2\x18\x03 \x01(\tR\x05line2\x12\x10\n" +
	"\x03age\x18\x04 \x01(\x02R\x03age\x127\n" +
	"\vpropogation\x18\x05 \x01(\v2\x15.satproto.PropogationR\vpropogation\"\x81\x01\n" +
	"\vPropogation\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\baltitude\x18\x04 \x01(\x02R\baltitude2`\n" +
	"\x12PropogationService\x12J\n" +
	"\x0eGetPropogation\x12\x1c.satproto.PropogationRequest\x1a\x1a.satproto.PropogationReplyB\vZ\tproto/v2/b\x06proto3"

var (
	file_proto_v2_sat_proto_rawDescOnce sync.Once
	file_proto_v2_sat_proto_rawDescData []byte
)

func file_proto_v2_sat_proto_rawDescGZIP() []byte {
	file_proto_v2_sat_proto_rawDescOnce.Do(func() {
		file_proto_v2_sat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v2_sat_proto_rawDesc), len(file_proto_v2_sat_proto_rawDesc)))
	})
	return file_proto_v2_sat_proto_rawDescData
}

var file_proto_v2_sat_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_v2_sat_proto_goTypes = []any{
	(*PropogationRequest)(nil), // 0: satproto.PropogationRequest
	(*PropogationReply)(nil),   // 1: satproto.PropogationReply
	(*Tle)(nil),                // 2: satproto.Tle
	(*Propogation)(nil),        // 3: satproto.Propogation
}
var file_proto_v2_sat_proto_depIdxs = []int32{
	2, // 0: satproto.PropogationReply.tle:type_name -> satproto.Tle
	3, // 1: satproto.PropogationReply.propogations:type_name -> satproto.Propogation
	3, // 2: satproto.Tle.propogation:type_name -> satproto.Propogation
	0, // 3: satproto.PropogationService.GetPropogation:input_type -> satproto.PropogationRequest
	1, // 4: satproto.PropogationService.GetPropogation:output_type -> satproto.PropogationReply
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_v2_sat_proto_init() }
func file_proto_v2_sat_proto_init() {
	if File_proto_v2_sat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v2_sat_proto_rawDesc), len(file_proto_v2_sat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v2_sat_proto_goTypes,
		DependencyIndexes: file_proto_v2_sat_proto_depIdxs,
		MessageInfos:      file_proto_v2_sat_proto_msgTypes,
	}.Build()
	File_proto_v2_sat_proto = out.File
	file_proto_v2_sat_proto_goTypes = nil
	file_proto_v2_sat_proto_depIdxs = nil
}
