// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.31.1
// source: proto/v2/sat.proto

// namespace

package v2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PropogationService_GetPropogation_FullMethodName = "/satproto.PropogationService/GetPropogation"
)

// PropogationServiceClient is the client API for PropogationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PropogationServiceClient interface {
	GetPropogation(ctx context.Context, in *PropogationRequest, opts ...grpc.CallOption) (*PropogationReply, error)
}

type propogationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPropogationServiceClient(cc grpc.ClientConnInterface) PropogationServiceClient {
	return &propogationServiceClient{cc}
}

func (c *propogationServiceClient) GetPropogation(ctx context.Context, in *PropogationRequest, opts ...grpc.CallOption) (*PropogationReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PropogationReply)
	err := c.cc.Invoke(ctx, PropogationService_GetPropogation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PropogationServiceServer is the server API for PropogationService service.
// All implementations must embed UnimplementedPropogationServiceServer
// for forward compatibility.
type PropogationServiceServer interface {
	GetPropogation(context.Context, *PropogationRequest) (*PropogationReply, error)
	mustEmbedUnimplementedPropogationServiceServer()
}

// UnimplementedPropogationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPropogationServiceServer struct{}

func (UnimplementedPropogationServiceServer) GetPropogation(context.Context, *PropogationRequest) (*PropogationReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPropogation not implemented")
}
func (UnimplementedPropogationServiceServer) mustEmbedUnimplementedPropogationServiceServer() {}
func (UnimplementedPropogationServiceServer) testEmbeddedByValue()                            {}

// UnsafePropogationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PropogationServiceServer will
// result in compilation errors.
type UnsafePropogationServiceServer interface {
	mustEmbedUnimplementedPropogationServiceServer()
}

func RegisterPropogationServiceServer(s grpc.ServiceRegistrar, srv PropogationServiceServer) {
	// If the following call panics, it indicates UnimplementedPropogationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PropogationService_ServiceDesc, srv)
}

func _PropogationService_GetPropogation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PropogationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropogationServiceServer).GetPropogation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PropogationService_GetPropogation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropogationServiceServer).GetPropogation(ctx, req.(*PropogationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PropogationService_ServiceDesc is the grpc.ServiceDesc for PropogationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PropogationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "satproto.PropogationService",
	HandlerType: (*PropogationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPropogation",
			Handler:    _PropogationService_GetPropogation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/v2/sat.proto",
}
