// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: proto/sat.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PropogationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoradCategory int32                  `protobuf:"varint,1,opt,name=NoradCategory,proto3" json:"NoradCategory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PropogationRequest) Reset() {
	*x = PropogationRequest{}
	mi := &file_proto_sat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropogationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropogationRequest) ProtoMessage() {}

func (x *PropogationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropogationRequest.ProtoReflect.Descriptor instead.
func (*PropogationRequest) Descriptor() ([]byte, []int) {
	return file_proto_sat_proto_rawDescGZIP(), []int{0}
}

func (x *PropogationRequest) GetNoradCategory() int32 {
	if x != nil {
		return x.NoradCategory
	}
	return 0
}

type PropogationReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tle           *TLE                   `protobuf:"bytes,1,opt,name=tle,proto3" json:"tle,omitempty"`
	Propogations  []*Propogation         `protobuf:"bytes,2,rep,name=propogations,proto3" json:"propogations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PropogationReply) Reset() {
	*x = PropogationReply{}
	mi := &file_proto_sat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropogationReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropogationReply) ProtoMessage() {}

func (x *PropogationReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropogationReply.ProtoReflect.Descriptor instead.
func (*PropogationReply) Descriptor() ([]byte, []int) {
	return file_proto_sat_proto_rawDescGZIP(), []int{1}
}

func (x *PropogationReply) GetTle() *TLE {
	if x != nil {
		return x.Tle
	}
	return nil
}

func (x *PropogationReply) GetPropogations() []*Propogation {
	if x != nil {
		return x.Propogations
	}
	return nil
}

type TLE struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Line1         string                 `protobuf:"bytes,2,opt,name=line1,proto3" json:"line1,omitempty"`
	Line2         string                 `protobuf:"bytes,3,opt,name=line2,proto3" json:"line2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLE) Reset() {
	*x = TLE{}
	mi := &file_proto_sat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLE) ProtoMessage() {}

func (x *TLE) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLE.ProtoReflect.Descriptor instead.
func (*TLE) Descriptor() ([]byte, []int) {
	return file_proto_sat_proto_rawDescGZIP(), []int{2}
}

func (x *TLE) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TLE) GetLine1() string {
	if x != nil {
		return x.Line1
	}
	return ""
}

func (x *TLE) GetLine2() string {
	if x != nil {
		return x.Line2
	}
	return ""
}

type Propogation struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Timestamp *Timestamp             `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// The latitude and longitude in degrees, using the WGS84 standard.
	LatLng *LatLng `protobuf:"bytes,2,opt,name=lat_lng,json=latLng,proto3" json:"lat_lng,omitempty"`
	// Using a float type for precision.
	AltitudeMeters float32 `protobuf:"fixed32,3,opt,name=altitude_meters,json=altitudeMeters,proto3" json:"altitude_meters,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Propogation) Reset() {
	*x = Propogation{}
	mi := &file_proto_sat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Propogation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Propogation) ProtoMessage() {}

func (x *Propogation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Propogation.ProtoReflect.Descriptor instead.
func (*Propogation) Descriptor() ([]byte, []int) {
	return file_proto_sat_proto_rawDescGZIP(), []int{3}
}

func (x *Propogation) GetTimestamp() *Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Propogation) GetLatLng() *LatLng {
	if x != nil {
		return x.LatLng
	}
	return nil
}

func (x *Propogation) GetAltitudeMeters() float32 {
	if x != nil {
		return x.AltitudeMeters
	}
	return 0
}

// https://github.com/googleapis/googleapis/blob/master/google/type/latlng.proto
// An object that represents a latitude/longitude pair. This is expressed as a
// pair of doubles to represent degrees latitude and degrees longitude. Unless
// specified otherwise, this must conform to the
// <a href="http://www.unoosa.org/pdf/icg/2012/template/WGS_84.pdf">WGS84
// standard</a>. Values must be within normalized ranges.
type LatLng struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The latitude in degrees. It must be in the range [-90.0, +90.0].
	Latitude float64 `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	// The longitude in degrees. It must be in the range [-180.0, +180.0].
	Longitude     float64 `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LatLng) Reset() {
	*x = LatLng{}
	mi := &file_proto_sat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatLng) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatLng) ProtoMessage() {}

func (x *LatLng) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatLng.ProtoReflect.Descriptor instead.
func (*LatLng) Descriptor() ([]byte, []int) {
	return file_proto_sat_proto_rawDescGZIP(), []int{4}
}

func (x *LatLng) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *LatLng) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

// https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/timestamp.proto
type Timestamp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Represents seconds of UTC time since Unix epoch 1970-01-01T00:00:00Z. Must
	// be between -62135596800 and 253402300799 inclusive (which corresponds to
	// 0001-01-01T00:00:00Z to 9999-12-31T23:59:59Z).
	Seconds int64 `protobuf:"varint,1,opt,name=seconds,proto3" json:"seconds,omitempty"`
	// Non-negative fractions of a second at nanosecond resolution. This field is
	// the nanosecond portion of the duration, not an alternative to seconds.
	// Negative second values with fractions must still have non-negative nanos
	// values that count forward in time. Must be between 0 and 999,999,999
	// inclusive.
	Nanos         int32 `protobuf:"varint,2,opt,name=nanos,proto3" json:"nanos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Timestamp) Reset() {
	*x = Timestamp{}
	mi := &file_proto_sat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Timestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timestamp) ProtoMessage() {}

func (x *Timestamp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timestamp.ProtoReflect.Descriptor instead.
func (*Timestamp) Descriptor() ([]byte, []int) {
	return file_proto_sat_proto_rawDescGZIP(), []int{5}
}

func (x *Timestamp) GetSeconds() int64 {
	if x != nil {
		return x.Seconds
	}
	return 0
}

func (x *Timestamp) GetNanos() int32 {
	if x != nil {
		return x.Nanos
	}
	return 0
}

var File_proto_sat_proto protoreflect.FileDescriptor

const file_proto_sat_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/sat.proto\x12\x13propogation_service\":\n" +
	"\x12PropogationRequest\x12$\n" +
	"\rNoradCategory\x18\x01 \x01(\x05R\rNoradCategory\"\x84\x01\n" +
	"\x10PropogationReply\x12*\n" +
	"\x03tle\x18\x01 \x01(\v2\x18.propogation_service.TLER\x03tle\x12D\n" +
	"\fpropogations\x18\x02 \x03(\v2 .propogation_service.PropogationR\fpropogations\"E\n" +
	"\x03TLE\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05line1\x18\x02 \x01(\tR\x05line1\x12\x14\n" +
	"\x05line2\x18\x03 \x01(\tR\x05line2\"\xaa\x01\n" +
	"\vPropogation\x12<\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1e.propogation_service.TimestampR\ttimestamp\x124\n" +
	"\alat_lng\x18\x02 \x01(\v2\x1b.propogation_service.LatLngR\x06latLng\x12'\n" +
	"\x0faltitude_meters\x18\x03 \x01(\x02R\x0ealtitudeMeters\"B\n" +
	"\x06LatLng\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\";\n" +
	"\tTimestamp\x12\x18\n" +
	"\aseconds\x18\x01 \x01(\x03R\aseconds\x12\x14\n" +
	"\x05nanos\x18\x02 \x01(\x05R\x05nanos2v\n" +
	"\x12PropogationService\x12`\n" +
	"\x0eGetPropogation\x12'.propogation_service.PropogationRequest\x1a%.propogation_service.PropogationReplyB\bZ\x06proto/b\x06proto3"

var (
	file_proto_sat_proto_rawDescOnce sync.Once
	file_proto_sat_proto_rawDescData []byte
)

func file_proto_sat_proto_rawDescGZIP() []byte {
	file_proto_sat_proto_rawDescOnce.Do(func() {
		file_proto_sat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sat_proto_rawDesc), len(file_proto_sat_proto_rawDesc)))
	})
	return file_proto_sat_proto_rawDescData
}

var file_proto_sat_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_sat_proto_goTypes = []any{
	(*PropogationRequest)(nil), // 0: propogation_service.PropogationRequest
	(*PropogationReply)(nil),   // 1: propogation_service.PropogationReply
	(*TLE)(nil),                // 2: propogation_service.TLE
	(*Propogation)(nil),        // 3: propogation_service.Propogation
	(*LatLng)(nil),             // 4: propogation_service.LatLng
	(*Timestamp)(nil),          // 5: propogation_service.Timestamp
}
var file_proto_sat_proto_depIdxs = []int32{
	2, // 0: propogation_service.PropogationReply.tle:type_name -> propogation_service.TLE
	3, // 1: propogation_service.PropogationReply.propogations:type_name -> propogation_service.Propogation
	5, // 2: propogation_service.Propogation.timestamp:type_name -> propogation_service.Timestamp
	4, // 3: propogation_service.Propogation.lat_lng:type_name -> propogation_service.LatLng
	0, // 4: propogation_service.PropogationService.GetPropogation:input_type -> propogation_service.PropogationRequest
	1, // 5: propogation_service.PropogationService.GetPropogation:output_type -> propogation_service.PropogationReply
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_sat_proto_init() }
func file_proto_sat_proto_init() {
	if File_proto_sat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sat_proto_rawDesc), len(file_proto_sat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_sat_proto_goTypes,
		DependencyIndexes: file_proto_sat_proto_depIdxs,
		MessageInfos:      file_proto_sat_proto_msgTypes,
	}.Build()
	File_proto_sat_proto = out.File
	file_proto_sat_proto_goTypes = nil
	file_proto_sat_proto_depIdxs = nil
}
